FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates tzdata && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /CLIProxyAPI

COPY release/cli-proxy-api-linux-amd64 /CLIProxyAPI/CLIProxyAPI
COPY config.example.yaml /CLIProxyAPI/config.example.yaml

WORKDIR /CLIProxyAPI

EXPOSE 8317

ENV TZ=Asia/Shanghai

RUN chmod +x /CLIProxyAPI/CLIProxyAPI

CMD ["./CLIProxyAPI"]
