.git
.github
release

auths
logs
conv
config.yaml

bin
.vscode
.claude
.codex
.codex-worktrees
.gemini
.serena
.agent
.agents
.antigravitycli
.opencode
.idea
.junie
.worktrees
.bmad
_bmad
_bmad-output

docs
README.md
README_CN.md
README_JA.md
LICENSE
